### ISSUE TITLE
Re: article

### ISSUE THREAD

**Issue by thurt** [amcdnl/debug-hell#1]
> Yes, im curious the difference between the runtime-regenerator and the transform-async-to-generator. 
http://masnun.com/2015/11/11/using-es7-asyncawait-today-with-babel.html

transform-async-to-generator plugin appears to transpile syntax of async/await into syntax of \*/yield. It also appears to make the behavior of those generator functions *act* like the intended async functions with a small code addition. **This is ES7 to ES6**

regenerator was created by Facebook team (See: https://facebook.github.io/regenerator/)– it transpiles generator functions into ES5-compliant syntax. In order to run those ES5 functions, however, requires the regeneratorRuntime code to be included with your code. If you use es2015 preset in Babel, it looks like it wraps each generator function with a hook into regeneratorRuntime–so the Babel es2015 preset is expecting you will include the regeneratorRuntime with your code. **regenerator is ES6 to ES5**

Just checked: es2015 preset behavior described in last paragraph is due to inclusion of transform-regenerator plugin.

**Comment by amcdnl** [comment]
Any questions re this?
